language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - hhvm

matrix:
    allow_failures:
        - php: 7.1
        - php: hhvm

before_script:
    - composer install --prefer-dist --no-interaction

script:
    - phpunit -c phpunit.xml.dist --coverage-text tests/Geocoder/Tests/Provider/BaiduProviderTest.php
    - phpunit -c phpunit.xml.dist --coverage-text tests/Geocoder/Tests/Provider/DataScienceToolkitProviderTest.php
    - phpunit -c phpunit.xml.dist --coverage-text tests/Geocoder/Tests/Provider/HereProviderTest.php
    - phpunit -c phpunit.xml.dist --coverage-text tests/Geocoder/Tests/Provider/IGNOpenLSProviderTest.php
    - phpunit -c phpunit.xml.dist --coverage-text tests/Geocoder/Tests/Provider/IpInfoProviderTest.php
    - phpunit -c phpunit.xml.dist --coverage-text tests/Geocoder/Tests/Provider/OGDViennaAustriaProviderTest.php
    - phpunit -c phpunit.xml.dist --coverage-text tests/Geocoder/Tests/Provider/OIORestProviderTest.php
